#!/bin/sh

# Prevent push if any of these commands fail
set -e

echo "Before pushing to origin, let's run some pre-push checks..."

echo "Checking for semver violations..."
cargo semver-checks || exit 1

echo "Running cargo clippy..."
cargo clippy -- -D warnings || exit 1

echo "Ensuring documentation generates correctly..."
cargo doc --no-deps || exit 1

echo "Checking if code compiles..."
cargo check || exit 1

echo "Checking is code is formatted..."
cargo fmt -- --check || exit 1

echo "Running tests..."
cargo test || exit 1

echo "All checks passed! Carry on!"
